export const PROJECT_DETAIL_MODAL_LABELS = {
  ubicacion: 'Ubicación',
  desde: 'Desde',
  comision: 'Comisión',
  valorComision: 'Valor comisión',
  lotes: 'Lotes disponibles',
  recursos: 'Recursos',
  videos: 'Videos',
  imagenes: 'Imágenes',
  imagen: 'Imagen',
  brochure: 'Brochure',
  planoPdf: 'PDF',
  compartir: 'Share',
  descargar: 'Descargar',
  seleccionarImagen: 'Seleccionar imagen',
  compartirWhatsApp: 'Compartir por WhatsApp',
  vistaPrevia: 'Vista previa',
  preparandoParaCompartir: 'Preparando archivo para compartir…',
  listoParaCompartir: 'Listo para compartir',
  errorPrepararCompartir: 'No se pudo preparar',
  errorPrepararCompartirDesc: 'Revisa tu conexión e inténtalo de nuevo.',
} as const;
